name: run-tests
on: [push]
jobs:
    test-ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: Install dependencies
              run: sudo apt install git python3 python3-tk python3-venv python3-dev tesseract-ocr libtesseract-dev libleptonica-dev pkg-config gcc g++ make
            - uses: actions/checkout@v2
            - name: Install Python dependencies
              uses: py-actions/py-dependency-install@v2
            - name: Run tests
              run: make test

    test-macos:
        runs-on: macos-latest
        steps:
            - name: Install dependencies
              run: brew install tesseract
            - uses: actions/checkout@v2
            - name: Set up Python environment
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install Python dependencies
              uses: py-actions/py-dependency-install@v2
            - name: Run tests
              run: make test

    test-windows:
        runs-on: windows-latest
        steps:
            - name: Install miniconda
              uses: conda-incubator/setup-miniconda@v2
              with:
                  auto-update-conda: true
                  python-version: 3.8
            - name: Install dependencies
              run: conda install -c conda-forge tesserocr=2.5.2 make
            - shell: bash -l {0}
              run: |
                  conda info
                  conda list
            - uses: actions/checkout@v2
            - name: Install Python dependencies
              shell: bash -l {0}
              run: pip install -r requirements.txt
            - name: Run tests
              shell: bash -l {0}
              run: make test
